//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using INC.DomainModel.Model;
namespace INC.DataAccessLayer.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncomingEntities : DbContext
    {
        public IncomingEntities()
            : base("name=IncomingEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<swift_msg_inc> swift_msg_inc { get; set; }
        public virtual DbSet<swift_msg_txt> swift_msg_txt { get; set; }
        public virtual DbSet<swift_prn> swift_prn { get; set; }
    }
}
