//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INC.DomainModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class swift_msg_inc
    {
        public decimal rec_no { get; set; }
        public decimal rec_id { get; set; }
        public string applic { get; set; }
        public string branchcode { get; set; }
        public System.DateTime date_in { get; set; }
        public Nullable<decimal> batch_id { get; set; }
        public string cod_stat { get; set; }
        public string complete_flg { get; set; }
        public Nullable<System.DateTime> swift_date { get; set; }
        public string swift_type { get; set; }
        public string file_name { get; set; }
        public string ref_no { get; set; }
        public string our_ref { get; set; }
        public string ar_pist_str { get; set; }
        public string ar_axia_str { get; set; }
        public string diak_no_str { get; set; }
        public Nullable<System.DateTime> diak_date { get; set; }
        public string swift_code { get; set; }
        public string sender_vostro { get; set; }
        public string oae { get; set; }
        public string stp { get; set; }
        public string for_proc { get; set; }
        public string for_reject { get; set; }
        public string for_auth { get; set; }
        public string for_check { get; set; }
        public string for_valeur { get; set; }
        public string ccy { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> embast { get; set; }
        public Nullable<decimal> axia_poso1 { get; set; }
        public Nullable<decimal> axia_poso2 { get; set; }
        public Nullable<decimal> axia_poso4 { get; set; }
        public string f71a { get; set; }
        public Nullable<decimal> f71g { get; set; }
        public string account { get; set; }
        public string account_ok { get; set; }
        public string @base { get; set; }
        public string f59_1 { get; set; }
        public string f59_base { get; set; }
        public string cust_account { get; set; }
        public string cust_ccy { get; set; }
        public string synal_code { get; set; }
        public string corresp { get; set; }
        public string corresp_ok { get; set; }
        public Nullable<decimal> timh { get; set; }
        public string timh_type { get; set; }
        public string dealref { get; set; }
        public string back_office { get; set; }
        public string nimexe { get; set; }
        public Nullable<System.DateTime> valeur1 { get; set; }
        public Nullable<System.DateTime> valeur2 { get; set; }
        public string corresp2 { get; set; }
        public Nullable<decimal> ben_key { get; set; }
        public string num_sess { get; set; }
        public Nullable<decimal> num_osn { get; set; }
        public Nullable<decimal> kod_aitisis { get; set; }
        public string eidos_aitisis { get; set; }
        public string rejected { get; set; }
        public string closed { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public Nullable<int> parent_rec_id { get; set; }
        public Nullable<int> batch_no { get; set; }
        public Nullable<int> swift_inc_group_no { get; set; }
        public string diak_no_inc { get; set; }
        public string diak_no_out { get; set; }
        public string date_serv { get; set; }
        public string satellitecode { get; set; }
        public string categ1 { get; set; }
        public string categ2 { get; set; }
        public string mt190 { get; set; }
        public string for_mt190 { get; set; }
        public string for_mt191 { get; set; }
        public string mt191 { get; set; }
        public string mt191_swift { get; set; }
        public Nullable<System.DateTime> mt191_date { get; set; }
        public string mt191_failed { get; set; }
        public string mt191_failed_error { get; set; }
        public Nullable<decimal> reply_swift { get; set; }
        public Nullable<System.DateTime> reply_date { get; set; }
        public string no_reply { get; set; }
        public string stp_error { get; set; }
        public string customer_soundex { get; set; }
        public Nullable<System.DateTime> email_to_cust { get; set; }
        public Nullable<System.DateTime> email_to_auth { get; set; }
        public Nullable<decimal> temp_id { get; set; }
        public Nullable<decimal> temp_no { get; set; }
        public string author { get; set; }
        public string f33b_2 { get; set; }
        public Nullable<System.DateTime> diak_date_inc { get; set; }
        public Nullable<System.DateTime> diak_date_out { get; set; }
        public string swift_no_out { get; set; }
        public Nullable<System.DateTime> swift_date_out { get; set; }
        public Nullable<System.DateTime> cust_valeur { get; set; }
        public Nullable<decimal> prom1 { get; set; }
        public string f20 { get; set; }
        public string f21 { get; set; }
        public Nullable<decimal> amt { get; set; }
        public string corresp1 { get; set; }
        public string dest0 { get; set; }
        public string cust_account_is_ok { get; set; }
        public string cust_account_is_iban { get; set; }
        public string mci_lock { get; set; }
        public string remarks { get; set; }
        public string date_ins { get; set; }
        public string time_ins { get; set; }
    }
}
