//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INC.DomainModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class swift_msg_txt
    {
        public decimal rec_no { get; set; }
        public decimal rec_id { get; set; }
        public string applic { get; set; }
        public string branchcode { get; set; }
        public System.DateTime date_in { get; set; }
        public string swift_type { get; set; }
        public string msg_txt { get; set; }
        public string file_name { get; set; }
    }
}
